//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroToleranceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public int ProductTotal { get; set; }
        public int OrderNumber { get; set; }
        public System.DateTime OrderTimestamp { get; set; }
        public int AddressID { get; set; }
    
        public virtual ADDRESS ADDRESS { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual USER USER { get; set; }
    }
}
